apiVersion: v1
kind: Service
metadata:
  name: viz-client
spec:
  selector:
    app: viz-client
  # type: NodePort
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
    # nodePort: 30000
