# This is a basic workflow to help you get started with Actions

name: demployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preinstall:
    runs-on: ubuntu-latest
    steps:
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
          yq --version
      - name: Install jq
        run: |
          sudo apt install -y jq
          jq --version

  build:
    runs-on: ubuntu-latest
    needs: preinstall

    env:
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      IMAGE: 85.192.34.50:5000/viz-client:${{github.sha}}

    steps:
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Add MCS.MailRU registry to Docker
        run: |
         sudo jq '. + {"insecure-registries": ["85.192.34.50:5000"]}' /etc/docker/daemon.json >daemon.json
         sudo mv daemon.json /etc/docker/daemon.json
         sudo systemctl restart docker

      - name: Login to registry
        run: |
          docker login 85.192.34.50:5000 --username registry --password ${REGISTRY_PASSWORD}

      - name: Build image
        run: |
          docker build -t 85.192.34.50:5000/viz-client:${{github.sha}} -f prod.dockerfile .

      - name: Push image
        run: |
          docker push 85.192.34.50:5000/viz-client:${{github.sha}}
      
      - name: Set K8s context
        uses: azure/k8s-set-context@v3
        with:
         method: service-account
         k8s-url: https://85.192.34.50:6443
         k8s-secret: ${{ secrets.KUBE_TOKEN }}
 
      - name: Deploy
        run: |
          cd chart
          helm upgrade --atomic --install --set image=${IMAGE} viz-client-release .
      
